### ISSUE TITLE
Changing the nameGenerator

### ISSUE THREAD

**Issue by pacifier007** [JPeer264/node-rename-css-selectors#31]
Please provide an option to replace the whole nameGenerator class. As in Node, the prototype won't help otherwise I would just use prototype to replace methods.

Why:

- To decrease class name conflicts or for personal preference.
- I don't want any class named "ad" as it's blocked by ad blockers.
- I am used to this feature as it exists in css-modules :) 

At the moment, I am using a mixed system where there are non-obfuscated classes in place too and it's a real pain due to class conflicts. I want to use a different naming generator.

Thanks.

**Comment by JPeer264** [comment]
Hi, thanks for your issue. This is actually a greay idea and not hard to implement (as far I could think of). 

You have any idea what kind of function you want to pass as alternative nameGenerator? Maybe we can pass another `generate` function?

**Comment by pacifier007** [comment]
Yes, a way to pass in our own generator function would be awesome. [This is an article](https://medium.freecodecamp.org/reducing-css-bundle-size-70-by-cutting-the-class-names-and-using-scope-isolation-625440de600b) with excellent example of a custom name generation method used in conjunction with generateScopedName feature of babel's css-modules plugin.

IMHO, we don't really need something that extensive. A simple option to use a custom name generator function will do. 
`'generator': className => { .. }`

**Comment by JPeer264** [comment]
Hey @pacifier007. I introduced `useCustomGenerator` in this PR https://github.com/JPeer264/node-rcs-core/pull/64. I am still not quite done yet because I need your help. In `useCustomGenerator` you have to pass in a function where a object is passed as parameter. In this object `type` is a key which the possible values: `keyframe`, `selector` or `attributeSelector`.

The only thing is that I have troubles with the type `attributeSelector` as you, as user, have to know what kind of attribute selector it is, that it won't crash the attribute selectors. The type `attributeSelector` means, that this passed class is matching any attribute selector of your passed CSS files.

As a small example what I mean. Let's say you have an attribute selector `[class=^begin]`, then you have to keep `begin` in the beginning of every class which matches it. So here my question. How do you want to handle such cases? Should I pass two extra keys with 1. the matching character: e.g. `^` or `$` and 2. the key what should stay the same? Or should I just pass the tail of the classes. E.g. if the class is `beginners` then I would just pass `ners` so you do not have to worry about the validation.

Or do you have another idea how it would make sense?

**Comment by JPeer264** [comment]
ping @pacifier007

**Comment by X-Ryl669** [comment]
It's in rcs-core now!
Preventing `ad` is indeed possible with the upcoming `reserved` array in the config file. These won't be generated anymore (without tweaking with the name generator at all). Yet, you can write your own too, and you'll have the information about what needs to be generated as the second argument (so when given an attribute selector, just call the default generator).
